plugins:
  elections_admin_moderator:
    client: true
    default: false
  elections_nav_category_list:
    client: true
    default: false
  elections_nominee_titles:
    client: true
    default: false
  elections_nominee_avatar_flair:
    client: true
    default: ''
  elections_enabled:
    client: true
    default: true
  elections_min_trust_to_self_nominate:
    default: 1
    enum: 'TrustLevelSetting'
  elections_status_banner_discovery:
    default: true
    client: true
  elections_status_banner_topic:
    default: true
    client: true
  elections_status_banner_default_result_hours:
    default: 48
    client: true
