plugins:
  elections_admin_moderator:
    client: true
    default: false
  elections_nav_category_list:
    client: true
    default: false
  elections_nominee_titles:
    client: true
    default: false
  elections_nominee_avatar_flair:
    client: true
    default: ''
